### ISSUE TITLE
Challenge Parsing fails with Base64 padding

### ISSUE THREAD

**Issue by jacohend** [Tierion/lsat-js#4]
Most Base64 encoders use `=` as byte padding. However,[ parseChallengePart](https://github.com/Tierion/lsat-js/blob/master/src/lsat.ts#L23) cannot process anymore than a single equal sign in an invoice or macaroon challenge part, which causes assert failures in cases where a challenger uses a Base64 encoder that pads. 

Replication: Use `LSAT macaroon="AgESMy4xMzYuMTc4LjE1OjM0MjM4AkIAAD2b0rX78LATiVo8bKgHuurefeF5OeX2H5ZuacBIK3+RAR1PKU1oZpfCZFib4zdDoj0pOpgPmhtuzNllU+y//D0AAAYgcWFs9FIteCzpCcEPSwmXKBpcx97hyL5Yt99cbLjRHzU=", invoice="lntb20n1psza5dwpp58kda9d0m7zcp8z2683k2spa6at08mcte88jlv8ukde5uqjpt07gsdzjfp85gnpqd9h8vmmfvdjjqurp09kk2mn5ypn8ymmdyppksctfdecx76twwssyxmmjv5sxcmny8gcnqvps8ycqzpgsp5m7xru8dlhrhmwjp8gynsj2l9mwan2jk52ah5xucrn9kc3p0pj5ns9qy9qsq7jjxypyyc7hvvs8srh6c3lvcp5l5wka94htnfxak99hd5qrx69sya9sj4zm3w5lncw0tksf944q73tduhlhs5apd63m9dte9dhva5dgqaceunx"` on the LSAT playground or in a simple lsat-js script. 

The solution (I think) would be to separate on the comma / whitespace first, then ensure that the first string split is `macaroon` or `invoice`.

It's also possible that my macaroon encoding is not supposed to require any padding, and that my LSAT implementation is wrong. But given that I'm adapting code from the Aperature project, I think this might be less likely.

**Comment by bucko13** [comment]
So it looks like there could be two problems here. The first is what you pointed out and is resolved in #6 

Unfortunately, to fully fix this will likely need a fix in an upstream dependency. Issue reporting the issue can be seen here: https://github.com/nitram509/macaroons.js/issues/51

**Comment by bucko13** [comment]
Resolved with #8
